name: Campus-iOS
options:
  bundleIdPrefix: de.tum
  xcodeVersion: "13.3"
  deploymentTarget: "15.0"
  groupSortPosition: top
  generateEmptyDirectories: true
  findCarthageFrameworks: true
  minimumXcodeGenVersion: "2.26.0"

targets:
  Campus-iOS:
    type: application
    platform: iOS
    deploymentTarget: 15.0
    sources:
      - path: Campus-iOS
    info:
      path: Campus-iOS/Info.plist
      properties:
        CFBundleVersion: "1.0.0"

    dependencies:
      - package: Alamofire
      - package: Firebase
        product: FirebaseAnalytics
      - package: Firebase
        product: FirebaseAnalyticsSwift-Beta
      - package: Firebase
        product: FirebaseCrashlytics
      - package: KeychainAccess
      - package: KVKCalendar
      - package: LRUCache
      - package: Snap
      - package: SwiftUICharts
      - package: SWXMLHash
      - package: XMLCoder

packages:
  Alamofire:
    url: https://github.com/Alamofire/Alamofire
    from: 5.5.0
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk.git
    from: 8.11.0
  KeychainAccess:
    url: https://github.com/kishikawakatsumi/KeychainAccess
    from: 4.2.2
  KVKCalendar:
    url: https://github.com/kvyatkovskys/KVKCalendar
    from: 0.5.8
  LRUCache:
    url: https://github.com/nicklockwood/LRUCache.git
    from: 1.0.2
  Snap:
    url: https://github.com/nerdsupremacist/Snap.git
    from: 0.2.2
  SwiftUICharts:
    url: https://github.com/willdale/SwiftUICharts
    from: 2.9.7
  SWXMLHash:
    url: https://github.com/drmohundro/SWXMLHash.git
    from: 6.0.0
  XMLCoder:
    url: https://github.com/MaxDesiatov/XMLCoder
    from: 0.13.1
